name: Build this project using Pygbag
on:
  push:
    branches:
      - main

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
