name: Build this project using Pygbag
on:
  push:
    branches:
      - main

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: build
        run: |
          echo "Installing pygbag"
          python3 -m pip install pygbag
          echo "pygbag success!"
          echo "building the project"
          python -m pygbag --build $GITHUB_WORKSPACE/main.py
          echo "DONE"
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GH_CREDENTIALS }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/build/web
