name: Build this project using Pygbag
on:
  push:
    branches:
      - main

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: build
        run: |
          echo "Installing pygbag"
          python3 -m pip install pygbag
          echo "pygbag success!"
          echo "building the project"
          python -m pygbag --build $GITHUB_WORKSPACE/py-singl-slider/main.py
          echo "DONE"
